Repository SoftStackFactory/retire-now, pull requests merged in 2018-08, with the labels that each got.

#81 Issue 73 dashboard modals
  src/app/app.module.ts
  src/pages/account/account.module.ts
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.module.ts
  src/pages/dashboard/dashboard.ts
  src/pages/input/input.module.ts
  src/pages/landing/landing.module.ts
  src/pages/login/login.module.ts
  src/pages/register/register.module.ts
  src/pages/results/results.module.ts
  src/pages/tutorial/tutorial.module.ts
Labels: reviewed

#86 Issue 82 error handling
  src/pages/login/login.html
  src/pages/login/login.module.ts
  src/pages/login/login.scss
  src/pages/login/login.ts
  src/pages/register/register.html
  src/pages/register/register.scss
  src/pages/register/register.ts
Labels: code review

#88 updated the set push to route to the correct pages
  src/pages/login/login.ts
  src/pages/register/register.ts
Labels: code review

#87 moved click here to register-button inside a card and added padding …
  src/pages/login/login.html
Labels: reviewed

#84 75 userinputvalidation
  src/pages/login/login.html
  src/pages/login/login.scss
  src/pages/login/login.ts
Labels: changes requested, code review

#85 75 a userregistervalidation
  src/pages/login/login.html
  src/pages/login/login.scss
  src/pages/register/register.html
  src/pages/register/register.ts
Labels: changes requested, code review

#89 Cleanup routing
  src/pages/account/account.html
  src/pages/account/account.ts
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.ts
  src/pages/login/login.ts
  src/pages/tutorial/tutorial.html
  src/pages/tutorial/tutorial.ts
Labels: reviewed

#90 Login/Register Cleanup
  src/pages/login/login.html
  src/pages/login/login.scss
  src/pages/login/login.ts
  src/pages/register/register.html
  src/pages/register/register.scss
  src/pages/register/register.ts
Labels: reviewed

#102 92 fra months calculation
  package-lock.json
  package.json
  src/app/app.component.ts
  src/providers/user/user.ts
Labels: code review

#98 75 userinputvalidation
  src/pages/input/input.html
  src/pages/input/input.scss
  src/pages/input/input.ts
  src/pages/login/login.html
  src/pages/login/login.scss
Labels: code review

#101 added light and dark for tan, green, and blue
  src/app/app.html
  src/app/app.scss
  src/pages/dashboard/dashboard.html
  src/pages/input/input.scss
  src/pages/login/login.html
  src/pages/login/login.scss
  src/pages/register/register.html
  src/pages/register/register.scss
  src/pages/results/results.html
  src/pages/results/results.scss
  src/pages/tabs/tabs.html
  src/pages/tabs/tabs.scss
  src/theme/variables.scss
Labels: code review

#111 Login fix
  src/environments/environments.ts
  src/pages/login/login.html
  src/pages/login/login.scss
Labels: reviewed

#112 Set isLoggedIn boolean to properly route tutorial skip buttons based …
  src/pages/tutorial/tutorial.html
  src/pages/tutorial/tutorial.ts
  src/providers/user/user.ts
Labels: code review

#105 update to account page.html
  src/pages/account/account.html
Labels: code review

#114 91 implementing backend
  package-lock.json
  src/pages/input/input.html
  src/pages/input/input.ts
  src/providers/user/user.ts
Labels: code review

#117 Tutorial skip button routing
  src/pages/account/account.ts
  src/pages/login/login.ts
Labels: reviewed

#131 Dasboard ng for
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.ts
  src/providers/user/user.ts
Labels: code review

#132 added red color to asterisk
  src/pages/login/login.html
Labels: code review

#133 have asterisk red color and floating
  src/pages/register/register.html
Labels: code review

#134 have asterisk red color and added tooltip function for frA$
  src/pages/input/input.html
Labels: code review

#135 fix routing issues with pages having tabs or no tabs
  src/pages/account/account.ts
  src/pages/login/login.ts
  src/pages/register/register.ts
  src/pages/tutorial/tutorial.html
  src/pages/tutorial/tutorial.ts
Labels: code review

#136 Added styling fixes to app.
  src/pages/account/account.html
  src/pages/input/input.scss
  src/pages/landing/landing.html
  src/pages/login/login.html
  src/pages/login/login.scss
  src/pages/register/register.html
  src/pages/register/register.scss
  src/pages/tutorial/tutorial.scss
  src/theme/variables.scss
Labels: code review

#138 add functionality to logout button in account.ts, actually sends logo…
  src/providers/user/user.ts
Labels: reviewed

#139 123 input page
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.ts
  src/pages/input/input.ts
  src/pages/results/results.html
  src/pages/results/results.ts
  src/providers/user/user.ts
Labels: code review

#140 adding empty user
  src/providers/user/user.ts
Labels: reviewed

#141 added on delete functionality to dashboardprofiles
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.ts
  src/providers/user/user.ts
Labels: code review

#142 fix for account page bug
  src/pages/account/account.ts
Labels: reviewed

#148 146-dashboard
  src/assets/imgs/receipt.png
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.ts
Labels: code review

#150 Modal fix
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.ts
  src/pages/results/results.html
  src/pages/results/results.ts
Labels: code review

#154 Issue 151 edit update
  src/pages/dashboard/dashboard.html
Labels: code review

#155 Misc Changes
  src/pages/account/account.ts
  src/pages/dashboard/dashboard.html
  src/pages/results/results.scss
Labels: reviewed

#160 145 input page
  package-lock.json
  src/pages/input/input.html
  src/pages/input/input.ts
  src/pages/register/register.ts
  src/providers/user/user.ts
Labels: code review

#161 profile name is displaying
  src/pages/results/results.html
  src/pages/results/results.ts
Labels: code review

#164 deleted change password button till furthur notice
  src/pages/account/account.html
Labels: reviewed

#167 125 dasbhoard
  src/pages/dashboard/dashboard.ts
  src/pages/input-edit/input-edit.html
  src/pages/input-edit/input-edit.module.ts
  src/pages/input-edit/input-edit.scss
  src/pages/input-edit/input-edit.ts
  src/providers/user/user.ts
Labels: code review

#169 125 dasbhoard
  src/app/app.module.ts
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.ts
  src/pages/input-edit/input-edit.html
  src/pages/input-edit/input-edit.ts
  src/providers/user/user.ts
Labels: code review

#170 updated scss to move around the header
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.scss
Labels: code review

#176 Issue 159 hover link
  src/pages/login/login.html
  src/pages/register/register.scss
Labels: code review

#171 added a back button on the register and login pages by implementing .…
  src/pages/landing/landing.ts
Labels: code review

#172 have title format consistent across the app by having the title star…
  src/pages/dashboard/dashboard.html
  src/pages/input/input.html
Labels: code review

#173 149 a enterkeyallforms
  src/pages/input/input.html
  src/pages/login/login.html
  src/pages/register/register.html
Labels: code review

#174 153-calulationIssue
  src/pages/input/input.ts
Labels: code review

#175 TabSwitch Issue
  src/pages/dashboard/dashboard.ts
Labels: code review

#180 163 tutorial skip
  src/app/app.module.ts
  src/environments/environments.ts
  src/pages/tabs/tabs.html
  src/pages/tabs/tabs.ts
  src/pages/tutorial/tutorial.html
  src/pages/tutorial/tutorial.ts
Labels: code review

#183 Issue 166 dashboard modal edit
  src/pages/dashboard/dashboard.ts
  src/pages/input/input.ts
  src/pages/results/results.html
  src/pages/results/results.ts
Labels: code review

#185 121 tutorial page
  src/assets/imgs/IMG_2974.PNG
  src/assets/imgs/IMG_2976.PNG
  src/assets/imgs/IMG_2977.PNG
  src/environments/environments.ts
  src/pages/tutorial/tutorial.html
  src/pages/tutorial/tutorial.scss
  src/pages/tutorial/tutorial.ts
Labels: code review

#186 121 tutorial page
  src/pages/tutorial/tutorial.html
Labels: code review

#187 Updated login option on register page
  src/pages/register/register.html
  src/pages/register/register.ts
Labels: code review

#188 184-dashboard no profiles
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/dashboard.ts
Labels: code review

#189 185 dateofbirtherror
  src/pages/login/login.html
  src/pages/login/login.ts
  src/pages/register/register.html
Labels: code review

#190 new registered users after a current user logs out are able to get to…
  src/pages/input/input.ts
  src/pages/register/register.ts
  src/providers/user/user.ts
Labels: code review

#194 Clean up Input
  src/pages/input-edit/input-edit.html
  src/pages/input/input.html
Labels: code review

#195 Get out of edit input
  src/pages/input-edit/input-edit.ts
  src/pages/results/results.html
  src/pages/results/results.ts
Labels: code review

#208 Comment dashboard
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/dashboard.ts
Labels: code review
