Repository SoftStackFactory/retire-now, pull requests merged in 2018-07, with the labels that each got.

#18 5 tutorial page
  src/pages/account/account.html
  src/pages/tutorial/tutorial.html
  src/pages/tutorial/tutorial.ts
Labels: code review

#17 9 account page
  src/pages/account/account.html
  src/pages/tutorial/tutorial.html
  src/pages/tutorial/tutorial.ts
Labels: code review

#16 2 login
  src/app/app.module.ts
  src/pages/login/login.html
Labels: code review

#14 7 results page
  src/app/app.module.ts
  src/pages/results/results.html
  src/pages/results/results.ts
Labels: code review

#12 Issue #8 dashboard
  src/app/app.module.ts
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/dashboard.ts
Labels: code review

#42 changed styling to better match wireframes and removed buttons
  src/pages/results/results.html
Labels: reviewed

#43 25 landing page
  src/pages/landing/landing.html
  src/pages/landing/landing.scss
  src/pages/landing/landing.ts
Labels: reviewed

#50 35 36 tutorial page
  src/pages/tutorial/tutorial.html
  src/pages/tutorial/tutorial.scss
  src/pages/tutorial/tutorial.ts
Labels: reviewed

#47 Issue #38 dashboard
  src/app/app.module.ts
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/dashboard.ts
Labels: reviewed

#52 45 finalize view
  src/pages/input/input.html
  src/pages/input/input.ts
Labels: code review

#51 39 40 Account page #2
  src/pages/account/account.html
Labels: code review

#53 30 a onlyinputvalidation
  src/pages/login/login.html
  src/pages/login/login.ts
Labels: code review

#54 Dev
  src/app/app.module.ts
  src/pages/account/account.html
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/dashboard.ts
  src/pages/landing/landing.html
  src/pages/landing/landing.scss
  src/pages/landing/landing.ts
  src/pages/login/login.html
  src/pages/login/login.ts
  src/pages/register/register.html
  src/pages/register/register.ts
  src/pages/results/results.html
  src/pages/tutorial/tutorial.html
  src/pages/tutorial/tutorial.scss
  src/pages/tutorial/tutorial.ts
Labels: release

#64 62 account
  src/pages/account/account.html
  src/pages/account/account.scss
Labels: code review

#67 changed landing page card content to fit on one page without scroll
  src/pages/landing/landing.html
Labels: code review

#68 replaced next button with arrows. Arrows are clickable to navigate an…
  src/pages/tutorial/tutorial.html
  src/pages/tutorial/tutorial.scss
  src/pages/tutorial/tutorial.ts
Labels: code review

#66 56-resultsPage
  src/app/app.module.ts
  src/pages/results/results.html
  src/pages/results/results.scss
Labels: code review

#65 Issue #60 dashboard
  ionic.config.json
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.ts
  src/pages/register/register.html
Labels: code review

#70 Issue #59 register
  src/pages/register/register.html
  src/pages/register/register.scss
Labels: code review

#74 63 loginchg
  src/pages/login/login.html
  src/pages/login/login.scss
  src/pages/login/login.ts
Labels: code review

#78 Adding tabs page, changing login route to tabs.
  src/pages/list/list.ts
  src/pages/login/login.html
  src/pages/login/login.ts
  src/pages/tabs/tabs.html
  src/pages/tabs/tabs.module.ts
  src/pages/tabs/tabs.scss
  src/pages/tabs/tabs.ts
Labels: reviewed

#69 61 inputchg
  src/pages/input/input.html
  src/pages/input/input.scss
  src/pages/login/login.html
Labels: code review

#79 bug fixes with back arrow and continue button appearing on first slide
  src/pages/tutorial/tutorial.html
  src/pages/tutorial/tutorial.ts
Labels: code review

#80 Issue 72 login register
  src/app/app.module.ts
  src/pages/login/login.html
  src/pages/login/login.ts
  src/pages/register/register.html
  src/pages/register/register.ts
  src/providers/user/user.ts
Labels: code review
